# Generated by Django 3.0.8 on 2020-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200720_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
