# Generated by Django 3.0.8 on 2020-11-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201127_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='element',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.Element'),
        ),
    ]
