# Generated by Django 3.0.8 on 2021-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210129_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_image',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
