# Generated by Django 3.0.8 on 2020-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200720_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='family',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tonal_range',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
