# Generated by Django 3.0.8 on 2020-08-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200812_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
