# Generated by Django 3.0.8 on 2020-08-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
