# Generated by Django 3.0.8 on 2020-09-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200921_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
