# Generated by Django 3.0.8 on 2020-10-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201021_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='elements', to='api.Instrument'),
        ),
    ]
