# Generated by Django 3.0.8 on 2020-11-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201113_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='elements',
        ),
        migrations.AlterField(
            model_name='element',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='elements', to='api.Instrument'),
        ),
    ]
