const genres = [
  'pop',
  'pop rap',
  'rap',
  'tropical house',
  'dance pop',
  'post-teen pop',
  'rock',
  'trap music',
  'hip hop',
  'southern hip hop',
  'latin',
  'pop rock',
  'dwn trap',
  'edm',
  'neo mellow',
  'alternative rock',
  'r&b',
  'classic rock',
  'latin pop',
  'album rock',
  'indie pop',
  'alternative metal',
  'indie rock',
  'mellow gold',
  'post-grunge',
  'viral pop',
  'hard rock',
  'singer-songwriter',
  'indie r&b',
  'pop punk',
  'folk-pop',
  'soft rock',
  'tropical',
  'reggaeton',
  'indie folk',
  'indietronica',
  'electro house',
  'nu metal',
  'permanent wave',
  'canadian pop',
  'gangster rap',
  'indie poptimism',
  'urban contemporary',
  'contemporary country',
  'hip pop',
  'country road',
  'country',
  'garage rock',
  'folk rock',
  'house',
  'big room',
  'latin hip hop',
  'rap metal',
  'rock en espanol',
  'stomp and holler',
  'funk rock',
  'soul',
  'dirty south rap',
  'chamber pop',
  'grupera',
  'europop',
  'underground hip hop',
  'regional mexican',
  'modern country rock',
  'blues-rock',
  'roots rock',
  'synthpop',
  'dance rock',
  'alternative dance',
  'new wave pop',
  'neo soul',
  'adult standards',
  'emo',
  'progressive house',
  'west coast rap',
  'new wave',
  'classic funk rock',
  'banda',
  'quiet storm',
  'latin alternative',
  'neo-psychedelic',
  'new rave',
  'psychedelic rock',
  'norteno',
  'deep big room',
  'spanish pop',
  'progressive electro house',
  'art rock',
  'rap rock',
  'trap latino',
  'funk',
  'teen pop',
  'motown',
  'shimmer pop',
  'electronic',
  'metal',
  'deep pop r&b',
  'deep indie r&b',
  'brostep',
  'deep tropical house',
  'crunk',
  'regional mexican pop',
  'screamo',
  'reggaeton flow',
  'escape room',
  'electronic trap',
  'punk',
  'new romantic',
  'disco',
  'pixie',
  'swedish pop',
  'acoustic pop',
  'new americana',
  'indie anthem-folk',
  'pop reggaeton',
  'metropopolis',
  'metalcore',
  'vapor soul',
  'focus',
  'hardcore hip hop',
  'deep german hip hop',
  'trap francais',
  'jazz blues',
  'brill building pop',
  'deep funk carioca',
  'folk',
  'francoton',
  'bass trap',
  'swedish idol pop',
  'southern rock',
  'east coast hip hop',
  'freak folk',
  'chillwave',
  'christian alternative rock',
  'talent show',
  'german hip hop',
  'vocal jazz',
  'groove metal',
  'dance-punk',
  'modern blues',
  'ranchera',
  'piano rock',
  'worship',
  'hollywood',
  'soundtrack',
  'boy band',
  'g funk',
  'lo-fi',
  'british blues',
  'redneck',
  'soul blues',
  'country rock',
  'new jack swing',
  'rock-and-roll',
  'christian music',
  'vegas indie',
  'argentine rock',
  'memphis soul',
  'ccm',
  'protopunk',
  'noise pop',
  'moombahton',
  'deep underground hip hop',
  'glam metal',
  'deep pop edm',
  'detroit hip hop',
  'mpb',
  'southern soul',
  'sertanejo universitario',
  'electric blues',
  'cantautor',
  'compositional ambient',
  'german pop',
  'traditional folk',
  'melodic metalcore',
  'britpop',
  'outlaw country',
  'christian rock',
  'downtempo',
  'deep dutch hip hop',
  'underground pop rap',
  'cumbia pop',
  'dream pop',
  'k-pop',
  'complextro',
  'alternative hip hop',
  'korean pop',
  'glam rock',
  'chicago soul',
  'tracestep',
  'deep australian indie',
  'funk metal',
  'traditional country',
  'grunge',
  'pop emo',
  'british invasion',
  'deep german pop rock',
  'indiecoustica',
  'deep groove house',
  'australian dance',
  'trip hop',
  'vapor twitch',
  'grime',
  'anthem worship',
  'speed metal',
  'scorecore',
  'pagode',
  'disco house',
  'italian arena pop',
  'italian pop',
  'melancholia',
  'classical',
  'channel pop',
  'indie psych-rock',
  'catstep',
  'lilith',
  'anti-folk',
  'samba',
  'mariachi',
  'reggae fusion',
  'swedish folk pop',
  'skate punk',
  'minimal dub',
  'slow core',
  'roots reggae',
  'video game music',
  'cumbia',
  'bubblegum pop',
  'nu gaze',
  'australian alternative rock',
  'la indie',
  'rockabilly',
  'deep trap',
  'duranguense',
  'jazz',
  'texas country',
  'german techno',
  'symphonic rock',
  'chillhop',
  'dancehall',
  'bachata',
  'progressive metal',
  'alt-indie rock',
  'bossa nova',
  'reggae',
  'candy pop',
  'otacore',
  'lift kit',
  'french pop',
  'nu jazz',
  'madchester',
  'merseybeat',
  'romantic',
  'comic',
  'deep latin hip hop',
  'progressive rock',
  'space rock',
  'power metal',
  'classify',
  'deep danish pop',
  'alternative country',
  'danish pop',
  'etherpop',
  'hoerspiel',
  'uk funky',
  'thrash metal',
  'spanish rock',
  'sky room',
  'sertanejo',
  'jam band',
  'eurodance',
  'trance',
  'deep cumbia sonidera',
  'nashville sound',
  'mandopop',
  'swedish indie rock',
  'finnish dance pop',
  'lounge',
  'taiwanese pop',
  'deep southern trap',
  'brazilian hip hop',
  'industrial metal',
  'french hip hop',
  'chamber psych',
  'jazz funk',
  'bolero',
  'deep euro house',
  'bow pop',
  'swedish alternative rock',
  'post-punk',
  'deep taiwanese pop',
  'shiver pop',
  'turkish pop',
  'alternative emo',
  'progressive trance',
  'cool jazz',
  'bubblegum dance',
  'forro',
  'finnish pop',
  'salsa',
  'c-pop',
  'show tunes',
  'world worship',
  'filter house',
  'nueva cancion',
  'preverb',
  'country dawn',
  'punk blues',
  'brooklyn indie',
  'post-screamo',
  'cabaret',
  'merengue',
  'power pop',
  'minimal',
  'opm',
  'swedish eurodance',
  'uk post-punk',
  'vocal house',
  'danspunk',
  'indie garage rock',
  'deep new americana',
  'axe',
  'chanson',
  'melodic death metal',
  'industrial rock',
  'jazz fusion',
  'deep regional mexican',
  'italian hip hop',
  'modern classical',
  'garage psych',
  'classic swedish pop',
  'turkish rock',
  'bebop',
  'post rock',
  'spanish pop rock',
  'deep swedish hip hop',
  'irish rock',
  'dutch pop',
  'movie tunes',
  'post-disco',
  'contemporary post-bop',
  'west coast trap',
  'swedish hip hop',
  'ninja',
  'texas blues',
  'cantopop',
  'blues',
  'dutch house',
  'anthem emo',
  'norwegian pop',
  'chillstep',
  'minimal techno',
  'chilean rock',
  'canadian indie',
  'experimental rock',
  'dutch hip hop',
  'acid jazz',
  'wrestling',
  'melodic hardcore',
  'easy listening',
  'fourth world',
  'progressive bluegrass',
  'microhouse',
  'big beat',
  'norwegian indie',
  'hip house',
  'post-hardcore',
  'vallenato',
  'rock gaucho',
  'broadway',
  'tech house',
  'indonesian pop',
  'traditional blues',
  'electro latino',
  'dreamo',
  'noise rock',
  'aussietronica',
  'french rock',
  'soul jazz',
  'antiviral pop',
  'sheffield indie',
  'australian pop',
  'country blues',
  'french indie pop',
  'swedish indie pop',
  'uplifting trance',
  'uk garage',
  'latin christian',
  'french indietronica',
  'hard bop',
  'swing',
  'country gospel',
  'ambient',
  'azontobeats',
  'russelater',
  'reggae rock',
  'lovers rock',
  'electro swing',
  'mexican indie',
  'epicore',
  'french reggae',
  'neo classical metal',
  'new age',
  'zapstep',
  'celtic rock',
  'turntablism',
  'death metal',
  'latin jazz',
  'industrial',
  'stoner rock',
  'nu disco',
  'indie rockism',
  'latin metal',
  'ska',
  'classic norwegian pop',
  'deep melodic euro house',
  'indie punk',
  'gauze pop',
  'deep funk',
  'swedish synthpop',
  'hyphy',
  'gothic metal',
  'progressive post-hardcore',
  'merengue urbano',
  'electro',
  'german metal',
  'deep chiptune',
  'drum and bass',
  'flamenco',
  'death core',
  'german pop rock',
  'suomi rock',
  'pinoy alternative',
  'canadian metal',
  'memphis blues',
  'ska punk',
  'brazilian gospel',
  'anime',
  'chicago blues',
  'drill',
  'christian uplift',
  'cumbia villera',
  'christian hip hop',
  'experimental',
  'stomp pop',
  'turkish jazz',
  'stride',
  'world',
  'deep ccm',
  'dub',
  'smooth jazz',
  'j-pop',
  'trova',
  'old school hip hop',
  'neue deutsche harte',
  'hardcore punk',
  'pub rock',
  'louvor',
  'afrobeats',
  'indie jazz',
  'new orleans blues',
  'spanish indie pop',
  'big band',
  'comedy',
  'mambo',
  'baroque',
  'icelandic pop',
  'acoustic blues',
  'pop house',
  'electroclash',
  'deep texas country',
  'delta blues',
  'shoegaze',
  'deep disco house',
  'new weird america',
  'deep swedish indie pop',
  'djent',
  'cowboy western',
  'cumbia sonidera',
  'turkish folk',
  'gospel',
  'finnish hip hop',
  'classical period',
  'symphonic metal',
  'swedish metal',
  'wonky',
  'norwegian rock',
  'minimal tech house',
  'melbourne bounce',
  'indonesian indie',
  'vaporwave',
  'groove room',
  'relaxative',
  'stoner metal',
  'tejano',
  'nwobhm',
  'piedmont blues',
  'sleep',
  'j-rock',
  'dansband',
  'desi',
  'filthstep',
  'drone',
  'bass music',
  'liquid funk',
  'argentine reggae',
  'gothic symphonic metal',
  'doo-wop',
  'celtic',
  'christian relaxative',
  'hardstyle',
  'alternative r&b',
  'spanish punk',
  'indian pop',
  'meditation',
  'boogaloo',
  'memphis hip hop',
  'afrobeat',
  'chicano rap',
  'cubaton',
  'operatic pop',
  'dangdut',
  'louisiana blues',
  'viking metal',
  'polish pop',
  'schlager',
  'contemporary jazz',
  'future garage',
  'british folk',
  'danish pop rock',
  'deep hardstyle',
  'desi hip hop',
  'hands up',
  'spanish hip hop',
  'crossover thrash',
  'underground rap',
  'k-hop',
  'healing',
  'intelligent dance music',
  'classic danish pop',
  'a cappella',
  'boston rock',
  'german indie',
  'environmental',
  'children’s music',
  'rumba',
  'deep house',
  'norwegian hip hop',
  'glitch hop',
  'arabesk',
  'velha guarda',
  'vapor pop',
  'mathcore',
  'jangle pop',
  'opera',
  'levenslied',
  'australian hip hop',
  'folk punk',
  'northern soul',
  'azonto',
  'electropowerpop',
  'sludge metal',
  'alternative pop rock',
  'abstract hip hop',
  'brazilian indie',
  'swamp blues',
  'nu-cumbia',
  'retro electro',
  'zolo',
  'jump blues',
  'spanish new wave',
  'filmi',
  'coverchill',
  'jazz metal',
  'liedermacher',
  'piano blues',
  'danseband',
  'neoclassical',
  'sleaze rock',
  'fingerstyle',
  'eurovision',
  'breakbeat',
  'deep turkish pop',
  'j-dance',
  'alternative ccm',
  'polynesian pop',
  'german punk',
  'riddim',
  'finnish metal',
  'brazilian punk',
  'welsh rock',
  'australian country',
  'glitch',
  'japanese r&b',
  'future funk',
  'j-rap',
  'reading',
  'italian indie pop',
  'rock steady',
  'portland indie',
  'folk metal',
  'bluegrass',
  'fluxwork',
  'technical death metal',
  'dutch rock',
  'uk drill',
  'canadian country',
  'christian metal',
  'grave wave',
  'stomp and flutter',
  'hardcore techno',
  'neo-singer-songwriter',
  'discofox',
  'float house',
  'russian pop',
  'electro jazz',
  'kiwi rock',
  'alternative pop',
  'deep uplifting trance',
  'slow game',
  'no wave',
  'turkish hip hop',
  'hard alternative',
  'scottish rock',
  'doom metal',
  'black metal',
  'folklore argentino',
  'progressive uplifting trance',
  'deep norteno',
  'cuban rumba',
  'j-metal',
  'neurofunk',
  'post-metal',
  'dark jazz',
  'polish hip hop',
  'chicago indie',
  'strut',
  'modern performance',
  'ectofolk',
  'jungle',
  'classic italian pop',
  'nasheed',
  'pop flamenco',
  'belgian rock',
  'austindie',
  'peruvian rock',
  'italo dance',
  'deathgrind',
  'jump up',
  'techno',
  'symphonic black metal',
  'pagan black metal',
  'british alternative rock',
  'kirtan',
  'orgcore',
  'malaysian pop',
  'christian dance',
  'idol',
  'irish folk',
  'new tribe',
  'brega',
  'western swing',
  'post-doom metal',
  'drift',
  'medieval rock',
  'bay area indie',
  'dark wave',
  'carnaval',
  'happy hardcore',
  'rap chileno',
  'puerto rican rock',
  'portuguese rock',
  'dubstep',
  'new orleans jazz',
  'soca',
  'russian rock',
  'classic finnish pop',
  'seattle indie',
  'electrofox',
  'chamame',
  'spanish noise pop',
  'ambeat',
  'albuquerque indie',
  'austropop',
  'italian disco',
  'arab pop',
  'italian pop rock',
  'hardcore',
  'gbvfi',
  'soul flow',
  'harmonica blues',
  'math pop',
  'baile funk',
  'brutal death metal',
  'progressive deathcore',
  'medieval',
  'salsa international',
  'melodipop',
  'celtic punk',
  'british indie rock',
  'quebecois',
  'grindcore',
  'psychedelic trance',
  'ethereal wave',
  'outsider house',
  'chicago house',
  'math rock',
  'garage pop',
  'romantico',
  'e6fi',
  'ebm',
  'rock catala',
  'psychedelic doom',
  'freestyle',
  'mexican rock-and-roll',
  'balearic',
  'colombian rock',
  'laiko',
  'nintendocore',
  'twee pop',
  'japanese city pop',
  'deep minimal techno',
  'barnmusik',
  'classic russian rock',
  'classic finnish rock',
  'indie dream pop',
  'bmore',
  'ska revival',
  'avantgarde metal',
  'entehno',
  'african gospel',
  'avant-garde jazz',
  'mande pop',
  'world fusion',
  'nordic house',
  'nu age',
  'brazilian ccm',
  'drill and bass',
  'warm drone',
  'polish punk',
  'straight edge',
  'free jazz',
  'swedish hard rock',
  'deep comedy',
  'acid house',
  'post-post-hardcore',
  'ye ye',
  'electro-industrial',
  'turbo folk',
  'chaotic hardcore',
  'funky tech house',
  'mashup',
  'speed garage',
  'destroy techno',
  'gothic rock',
  'canterbury scene',
  'sertanejo tradicional',
  'dansktop',
  'bassline',
  'oi',
  'j-idol',
  'nursery',
  'deep latin christian',
  'african rock',
  'gypsy jazz',
  'k-indie',
  'christian hardcore',
  'singaporean pop',
  'romanian pop',
  'retro metal',
  'emo punk',
  'classic garage rock',
  'surf music',
  'kindermusik',
  'classic chinese pop',
  'substep',
  'kraut rock',
  'world meditation',
  'argentine indie',
  'futurepop',
  'laboratorio',
  'tango',
  'classical performance',
  'vancouver indie',
  'mandible',
  'russiavision',
  'slovak pop',
  'steampunk',
  'fado',
  'old-time',
  'chill lounge',
  'bhangra',
  'volksmusik',
  'freakbeat',
  'christian punk',
  'norwegian metal',
  'hawaiian',
  'cello',
  'dixieland',
  'psychobilly',
  'canzone napoletana',
  'punjabi',
  'danish hip hop',
  'horror punk',
  'alternative roots rock',
  'orchestral',
  'atmospheric black metal',
  'musica para ninos',
  'zouk riddim',
  'uk hip hop',
  'comedy rock',
  'athens indie',
  'gabba',
  'latin electronica',
  'early music',
  'turkish alternative',
  'drone metal',
  'kabarett',
  'deep talent show',
  'classical piano',
  'j-poprock',
  'swedish reggae',
  'choro',
  'psychill',
  'columbus ohio indie',
  'progressive psytrance',
  'venezuelan rock',
  'persian pop',
  'italian metal',
  'theme',
  'detroit techno',
  'neo-trad metal',
  'jazz trio',
  'russian hip hop',
  'deep latin alternative',
  'p funk',
  'czech rock',
  'abstract beats',
  'hungarian rock',
  'israeli rock',
  'ballroom',
  'swedish jazz',
  'aggrotech',
  'electro bailando',
  'deep indian pop',
  'praise',
  'kizomba',
  'power-pop punk',
  'bubble trance',
  'ok indie',
  'progressive trance house',
  'neo-progressive',
  'avant-garde',
  'vintage italian soundtrack',
  'hungarian pop',
  'swedish punk',
  'dub techno',
  'black thrash',
  'choral',
  'voidgaze',
  'tribal house',
  'popgaze',
  'indie psych-pop',
  'visual kei',
  'anime score',
  'melodic hard rock',
  'power blues-rock',
  'andean',
  'dark cabaret',
  'shimmer psych',
  'french movie tunes',
  'goregrind',
  'deep pop punk',
  'exotica',
  'classic colombian pop',
  'barnemusikk',
  'basque rock',
  'mizrahi',
  'rai',
  'czech folk',
  'folkmusik',
  'classic turkish pop',
  'horrorcore',
  'perth indie',
  'deep chill',
  'renaissance',
  'j-indie',
  'fidget house',
  'deep melodic metalcore',
  'violin',
  'nu skool breaks',
  'christelijk',
  'highlife',
  'string quartet',
  'timba',
  'chiptune',
  'belly dance',
  'zouk',
  'vintage swedish pop',
  'brass band',
  'russian punk',
  'kids dance party',
  'classic peruvian pop',
  'acid techno',
  'southern gospel',
  'sega',
  'lds',
  'vienna indie',
  'turkish classical',
  'mod revival',
  'neue deutsche welle',
  'deep liquid',
  'spanish reggae',
  'norwegian gospel',
  'digital hardcore',
  'deep soul house',
  'albanian pop',
  'c86',
  'french folk pop',
  'bouncy house',
  'girl group',
  'classic icelandic pop',
  'polish reggae',
  'thai idol',
  'swiss rock',
  'hip hop tuga',
  'college a cappella',
  'instrumental post rock',
  'irish country',
  'dominican pop',
  'native american',
  'uk dub',
  'southern soul blues',
  'bounce',
  'jazz bass',
  'rio de la plata',
  'hauntology',
  'catalan folk',
  'nordic folk',
  'miami bass',
  'arab folk',
  'yugoslav rock',
  'ambient idm',
  'swamp pop',
  'classic belgian pop',
  'beats',
  'classic polish pop',
  'spanish folk',
  'vintage french electronic',
  'riot grrrl',
  'free improvisation',
  'hip hop quebecois',
  'shibuya-kei',
  'garage punk',
  'pakistani pop',
  'harpsichord',
  'tin pan alley',
  'musica nativista',
  'classical guitar',
  'appalachian folk',
  'deep christian rock',
  'morna',
  'thai pop',
  'desert blues',
  'cante flamenco',
  'new age piano',
  'samba-enredo',
  'polish indie',
  'vintage tango',
  'balkan brass',
  'thrash core',
  'italian jazz',
  'atmospheric post rock',
  'estonian pop',
  'chanson quebecois',
  'croatian pop',
  'soukous',
  'qawwali',
  'boogie-woogie',
  'brazilian composition',
  'czech hip hop',
  'modern uplift',
  'serialism',
  'disco polo',
  'stomp and whittle',
  'neo-rockabilly',
  'hiplife',
  'workout',
  'deep tech house',
  'karneval',
  'underground latin hip hop',
  'kompa',
  'electropunk',
  'melodic power metal',
  'drumfunk',
  'metal guitar',
  'portuguese pop',
  'tico',
  'finnish indie',
  'ecuadoria',
  'electronica',
  'cyber metal',
  'german oi',
  'full on',
  'kwaito house',
  'vietnamese pop',
  'vocaloid',
  'heavy alternative',
  'outsider',
  'deep flow',
  'irish indie',
  'gothic alternative',
  'jumpstyle',
  'k-rock',
  'crust punk',
  'psych gaze',
  'fake',
  'german show tunes',
  'brutal deathcore',
  'orquesta tropical',
  'ethiopian pop',
  'blackgaze',
  'calypso',
  'slovak hip hop',
  'mbalax',
  'grunge pop',
  'beatdown',
  'rosary',
  'composition d',
  'latvian pop',
  'j-ambient',
  'traditional rock ‘n roll',
  'rva indie',
  'dark black metal',
  'alternative americana',
  'deep acoustic pop',
  'classic venezuelan pop',
  'witch house',
  'orquesta tipica',
  'austrian hip hop',
  'concert piano',
  'electro dub',
  'ragtime',
  'louisville indie',
  'drone folk',
  'canadian hip hop',
  'lounge house',
  'hungarian hip hop',
  'ukrainian rock',
  'neofolk',
  'world chill',
  'traditional ska',
  'denver indie',
  'deep smooth jazz',
  'anarcho-punk',
  'oshare kei',
  'yoik',
  'leeds indie',
  'geek rock',
  'indie emo',
  'funk carioca',
  'abstract',
  'traditional british folk',
  'dirty texas rap',
  'judaica',
  'japanese psychedelic',
  'classic czech pop',
  'deep dance pop',
  'broken beat',
  'deep rai',
  'lithumania',
  'hard minimal techno',
  'lo star',
  'modern southern rock',
  'neo-synthpop',
  'nwothm',
  'zouglou',
  'makossa',
  'footwork',
  'zillertal',
  'acousmatic',
  'mexican son',
  'ukulele',
  'deep gothic post-punk',
  'deep soundtrack',
  'swiss hip hop',
  'deep neofolk',
  'tone',
  'ghazal',
  'deep contemporary country',
  'psychedelic blues-rock',
  'musiikkia lapsille',
  'semba',
  'deep adult standards',
  'islamic recitation',
  'blaskapelle',
  'guidance',
  'kurdish folk',
  'tribute',
  'atmospheric post-metal',
  'darkstep',
  'vegan straight edge',
  'nerdcore',
  'new beat',
  'crack rock steady',
  'swedish prog',
  'danish indie',
  'belgian indie',
  'slavic metal',
  'classic soundtrack',
  'slc indie',
  'classic french pop',
  'kayokyoku',
  'electro trash',
  'traditional swing',
  'garage punk blues',
  'deep german punk',
  'deep discofox',
  'indian classical',
  'classic afrobeat',
  'black death',
  'dark hardcore',
  'minimal wave',
  'zydeco',
  'downtempo fusion',
  'jazz brass',
  'australian indie',
  'underground power pop',
  'gothic americana',
  'traditional scottish folk',
  'classic dutch pop',
  'nl folk',
  'didgeridoo',
  'schranz',
  'funky breaks',
  'motivation',
  'indie singer-songwriter',
  'spanish invasion',
  'euroska',
  'ragga jungle',
  'breakcore',
  'library music',
  'deep psychobilly',
  'michigan indie',
  'chalga',
  'electronicore',
  'corrosion',
  'south african jazz',
  'usbm',
  'solipsynthm',
  'progressive alternative',
  'neurostep',
  'deep brazilian pop',
  'deep orchestral',
  'deep melodic hard rock',
  'string folk',
  'dark ambient',
  'mallet',
  'deep disco',
  'power violence',
  'contemporary composition',
  'fast melodic punk',
  'finnish hardcore',
  'martial industrial',
  'classic russian pop',
  'hindustani classical',
  'enka',
  'russian alternative',
  'minimal melodic techno',
  'beach music',
  'japanese jazztronica',
  'neo metal',
  'rebetiko',
  'future ambient',
  'tzadik',
  'kwaito',
  'liturgical',
  'abstract idm',
  'ostrock',
  'gospel reggae',
  'faroese pop',
  'musica per bambini',
  'melodic progressive metal',
  'monastic',
  'scratch',
  'ambient psychill',
  'string band',
  'french punk',
  'panpipe',
  'afrikaans',
  'japanoise',
  'power electronics',
  'byzantine',
  'russian folk',
  'gamecore',
  'rap metalcore',
  'traditional soul',
  'coupe decale',
  'musique pour enfants',
  'consort',
  'bass trip',
  'porro',
  'norwegian jazz',
  'italian progressive rock',
  'galego',
  'hard house',
  'bossa nova jazz',
  'spanish classical',
  'classic schlager',
  'nz indie',
  'slam death metal',
  'bemani',
  'manele',
  'deep opera',
  'deep progressive trance',
  'deep liquid bass',
  'magyar',
  'german ccm',
  'deep ambient',
  'polyphony',
  'deep soft rock',
  'iskelma',
  'bay area hip hop',
  'wind ensemble',
  'shanty',
  'military band',
  'romanian rock',
  'luk thung',
  'greek indie',
  'funeral doom',
  'flick hop',
  'chaotic black metal',
  'deep folk metal',
  'armenian folk',
  'skinhead reggae',
  'tekno',
  'italian folk',
  'screamocore',
  'marching band',
  'indie fuzzpop',
  'persian traditional',
  'neo-pagan',
  'dark psytrance',
  'african percussion',
  'go-go',
  'spoken word',
  'breton folk',
  'vapor house',
  'depressive black metal',
  'minimal dubstep',
  'jig and reel',
  'deep canadian indie',
  'experimental psych',
  'deep sunset lounge',
  'indie shoegaze',
  'vintage chanson',
  'harp',
  'swedish pop punk',
  'indorock',
  'punta',
  'kuduro',
  'thrash-groove metal',
  'doujin',
  'cornetas y tambores',
  'accordion',
  'pipe band',
  'ghettotech',
  'corsican folk',
  'speedcore',
  'outer hip hop',
  'jazz orchestra',
  'danish jazz',
  'trash rock',
  'indie pop rock',
  'jug band',
  'remix',
  'benga',
  'neo-industrial rock',
  'west african jazz',
  'nepali',
  'hebrew pop',
  'bulgarian rock',
  'geek folk',
  'deep darkpsy',
  'deep happy hardcore',
  'blues-rock guitar',
  'klezmer',
  'triangle indie',
  'black sludge',
  'deep german indie',
  'barbershop',
  'greek hip hop',
  'brass ensemble',
  'j-core',
  'dark minimal techno',
  'screamo punk',
  'cumbia funk',
  'greek house',
  'zim',
  'technical brutal death metal',
  'ambient fusion',
  'deep jazz guitar',
  'italian punk',
  'british dance band',
  'hard glam',
  'chinese traditional',
  'commons',
  'dallas indie',
  'light music',
  'deep deep house',
  'northern irish indie',
  'sinhala',
  'j-reggae',
  'gospel blues',
  'power noise',
  'abstractro',
  'throat singing',
  'street punk',
  'capoeira',
  'post-disco soul',
  'drama',
  'deep vocal house',
  'deep vocal jazz',
  'vintage jazz',
  'deep melodic death metal',
  'deep indie singer-songwriter',
  'mantra',
  'british brass band',
  'contemporary folk',
  'chinese indie rock',
  'finnish jazz',
  'deep psytrance',
  'soda pop',
  'unblack metal',
  'traditional funk',
  'fussball',
  'deep ragga',
  'deep new wave',
  'covertrance',
  'deep full on',
  'deep southern soul',
  'steelpan',
  'cajun',
  'stl indie',
  'japanese traditional',
  'poetry',
  'dubsteppe',
  'carnatic',
  'makina',
  'deep indie pop',
  'classic eurovision',
  'noise punk',
  'slash punk',
  'spanish indie rock',
  'c64',
  'college marching band',
  'muziek voor kinderen',
  'grisly death metal',
  'gothic post-punk',
  'musique concrete',
  'chamber choir',
  'oratory',
  'hardcore breaks',
  'deep east coast hip hop',
  'deep funk house',
  'mexican traditional',
  'classical organ',
  'classical flute',
  'fallen angel',
  'skiffle',
  'sunset lounge',
  'organic ambient',
  'bangla',
  'belorush',
  'deep indie rock',
  'traditional reggae',
  'spytrack',
  'early music ensemble',
  'polka',
  'deep freestyle',
  'neo soul-jazz',
  'deep progressive house',
  'contemporary classical',
  'electroacoustic improvisation',
  'traditional rockabilly',
  'halloween',
  'clarinet',
  'deep jazz piano',
  'deep jazz fusion',
  'indian rock',
  'deep downtempo fusion',
  'crossover prog',
  'deep classic garage rock',
  'experimental dubstep',
  'dubstep product',
  'football',
  'glitch beats',
  'skinhead oi',
  'polish jazz',
  'villancicos',
  'deep chill-out',
  'deep g funk',
  'classic psychedelic rock',
  'punk ska',
  'deep filthstep',
  'deep nordic folk',
  'skweee',
  'deep northern soul',
  'deep pop emo',
  'deep hardcore',
  'goa trance',
  'deep surf music',
  'klapa',
  'baroque ensemble',
  'gamelan',
  'deep swedish rock',
  'deep thrash metal',
  'deep italo disco',
  'hatecore',
  'demoscene',
  'raw black metal',
  'hard stoner rock',
  'norwegian punk',
  'slovenian rock',
  'wrock',
  'dark progressive house',
  'accordeon',
  're:techno',
  'ambient dub techno',
  'neo honky tonk',
  'maghreb',
  'charred death',
  'chill groove',
  'breaks',
  'kc indie',
  'modern downshift',
  'vintage swing',
  'guitar case',
  'tibetan',
  'deep punk rock',
  'noise',
  'deep free jazz',
  'deep motown',
  'j-punk',
  'tanzlmusi',
  'italo beats',
  'glitter trance',
  'malagasy folk',
  'lowercase',
  'chill-out trance',
  'new jack smooth',
  'deep nz indie',
  'twin cities indie',
  'deep eurodance',
  'deep power-pop punk',
  'grim death metal',
  'alternative hardcore',
  'deep dub techno',
  'j-poppunk',
  'deep space rock',
  'deep cello',
  'vintage rockabilly',
  'chinese experimental',
  'terrorcore',
  'zeuhl',
  'doomcore',
  'chinese opera',
  'indie emo rock',
  'french folk',
  'jangle rock',
  'german street punk',
  'nu electro',
  'deep hardcore punk',
  'rhythm and boogie',
  'alternative metalcore',
  'ceilidh',
  'bulgarian folk',
  'modern free jazz',
  'thai indie',
  'deep neo-synthpop',
  'heavy gothic rock',
  'ghoststep',
  'jazz composition',
  'cryptic black metal',
  'deep classical piano',
  'ethereal gothic',
  'deep orgcore',
  'vintage schlager',
  'swedish jazz orkester',
  'song poem',
  'vintage country folk',
  'gothic doom',
  'vintage gospel',
  'chip hop',
  'deep delta blues',
  'deep german jazz',
  'twee indie pop',
  'dark electro-industrial',
  'neo-traditional country',
  'cinematic dubstep',
  'deep symphonic black metal',
  'saxophone',
  'deep breakcore',
  'anime cv',
  'caucasian folk',
  'necrogrind',
  'deep latin jazz',
  'smooth urban r&b',
  'vintage swoon',
  'central asian folk',
  'vintage reggae',
  'drone psych',
  'deep deep tech house',
  'vintage western',
  'rock noise',
  'deep string quartet'
]

export default genres
