# Generated by Django 3.0.8 on 2020-07-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('start', models.FloatField(blank=True)),
                ('duration', models.FloatField(blank=True)),
                ('loudness', models.FloatField(blank=True)),
                ('tempo', models.FloatField(blank=True)),
                ('key', models.IntegerField(blank=True)),
                ('mode', models.IntegerField(blank=True)),
                ('learned', models.BooleanField()),
                ('time_signature', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('tonal_range', models.CharField(max_length=200)),
                ('picture', models.ImageField(
                    blank=True, upload_to='photos/%Y/%m/%d/')),
                ('year', models.CharField(max_length=4)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(blank=True)),
                ('explicit', models.BooleanField(default=False)),
                ('key', models.IntegerField(blank=True)),
                ('mode', models.IntegerField(blank=True)),
                ('lyrics', models.TextField(blank=True)),
                ('time_signature', models.IntegerField(blank=True)),
                ('tempo', models.FloatField(blank=True)),
                ('acousticness', models.FloatField(blank=True)),
                ('danceability', models.FloatField(blank=True)),
                ('energy', models.FloatField(blank=True)),
                ('instrumentalness', models.FloatField(blank=True)),
                ('liveness', models.FloatField(blank=True)),
                ('loudness', models.FloatField(blank=True)),
                ('speechiness', models.FloatField(blank=True)),
                ('valence', models.FloatField(blank=True)),
                ('original', models.BooleanField(default=False)),
                ('spotify_url', models.CharField(blank=True, max_length=200)),
                ('spotify_id', models.CharField(blank=True, max_length=200)),
                ('instruments', models.ManyToManyField(to='app.Instrument')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('element', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.Element')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='instrument',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.Instrument'),
        ),
        migrations.AddField(
            model_name='element',
            name='song',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.Song'),
        ),
    ]
