# Generated by Django 3.0.8 on 2020-07-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_element_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
