# Generated by Django 3.0.8 on 2020-07-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200724_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
