# Generated by Django 3.0.8 on 2020-08-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20200812_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='instrument',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app.Instrument'),
        ),
        migrations.AlterField(
            model_name='element',
            name='song',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app.Song'),
        ),
        migrations.AlterField(
            model_name='element',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='elements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='element',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.Element'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='instruments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
