# Generated by Django 3.0.8 on 2020-09-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200916_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.Instrument'),
        ),
    ]
