# Generated by Django 3.0.8 on 2020-09-21 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20200916_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='instruments', to='app.Instrument'),
        ),
        migrations.AlterField(
            model_name='element',
            name='song',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app.Song'),
        ),
        migrations.AlterField(
            model_name='element',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
