# Generated by Django 3.0.8 on 2020-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201022_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='elements',
            field=models.ManyToManyField(blank=True, to='api.Element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='api.Instrument'),
        ),
    ]
