# Generated by Django 3.0.8 on 2021-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_song_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
