export const instrumentList = [
  'Accordion',
  'Air horn',
  'Bagpipe',
  'Balalaika',
  'Banjo',
  'Barrel drum',
  'Bass drum',
  'Bassoon',
  'Beatboxing',
  'Bongo drums',
  'Celesta',
  'Clarinet',
  'Cymbal',
  'Didgeridoo',
  'Djembe',
  'Drum',
  'Drum kit',
  'Drum machine',
  'Electric Guitar',
  'Electronic organ',
  'English horn',
  'Euphonium',
  'Fingerboard synthesizer',
  'Flugelhorn',
  'Flute',
  'French horn',
  'Glockenspiel',
  'Goblet drum',
  'Guitar',
  'Hammond organ',
  'Handpan',
  'Harmonica',
  'Harp',
  'Harpsichord',
  'Kazoo',
  'Keyboard',
  'Keytar',
  'Lute',
  'Maktoum',
  'Mandolin',
  'Mellotron',
  'MIDI keyboard',
  'Oboe',
  'Ocarina',
  'Octa-Vibraphone',
  'Pan flute',
  'Piano ',
  'Piccolo',
  'Pipe organ',
  'Recorder',
  'Saxophone',
  'Sitar',
  'Slide trumpet',
  'Snare',
  'Sousaphone',
  'Spoon',
  'Steelpan',
  'Synthesizer',
  'Theremin',
  'Timpani (kettledrum)',
  'Tom-tom',
  'Triangle',
  'Trombone',
  'Trumpet',
  'Tsymbaly',
  'Tuba',
  'Turntable',
  'Ukulele',
  'Vibraphone',
  'Viola ',
  'Violin',
  'Voice',
  'Wood block',
  'Xylophone',
  'Other'
]

export const instrumentFamilies = ['Woodwind', 'Brass', 'String', 'Percussion', 'Other']
export const instrumentTonalities = ['Soprano', 'Alto', 'Tenor', 'Baritone', 'Bass', 'N/A']
